source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'TDRoundedNavigationBar_Example', :exclusive => true do
  pod "TDRoundedNavigationBar", :path => "../"
end

target 'TDRoundedNavigationBar_Tests', :exclusive => true do
  pod "TDRoundedNavigationBar", :path => "../"

  
end
